apiVersion: apps/v1
kind: Deployment
metadata:
        name: pythontest
spec:
    selector:
       matchLabels:
          app: pythontest
    replicas: 1 
    template:
       metadata:
         labels:
            app: pythontest
       spec:
          containers:
            - name: pythontest
              image: <dockerimageurl>
              env:
                 - name: ATC_PASSWORD
                   valueFrom:
                       secretKeyRef:
                          name: appenvs
                          key: atcpassword
                 - name: ATC_USERNAME
                   value: "ATCUSER01"
              ports: 
              - containerPort: 8000
